version: '3'
services:
  anonymization-service:
    build: ./
    environment:
    - NODE_ENV=${NODE_ENV}
    - HTTP_PORT=8080
    - SSL_KEY=${SSL_KEY}
    - SSL_CERT=${SSL_CERT}
    - INTERNAL_DOMAIN_LIST=${INTERNAL_DOMAIN_LIST}
    - ANONYMIZE_EXTRENAL_EMAIL_DOMAIN=${ANONYMIZE_EXTRENAL_EMAIL_DOMAIN}
    - ANONYMIZE_EXTRENAL_EMAIL_USERNAME=${ANONYMIZE_EXTRENAL_EMAIL_USERNAME}
    - ANONYMIZE_INTERNAL_EMAIL_DOMAIN=${ANONYMIZE_INTERNAL_EMAIL_DOMAIN}
    - ANONYMIZE_INTERNAL_EMAIL_USERNAME=${ANONYMIZE_INTERNAL_EMAIL_USERNAME}
    - ANONYMIZATION_SALT=${ANONYMIZATION_SALT}
    - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
    - GSUITE_CLIENT_EMAIL=${GSUITE_CLIENT_EMAIL}
    - GSUITE_PRIVATE_KEY=${GSUITE_PRIVATE_KEY}
    - GSUITE_SCOPES=${GSUITE_SCOPES}
    - API_TOKEN=${API_TOKEN}
    - O365_TENANT_ID=${O365_TENANT_ID}
    - O365_CLIENT_ID=${O365_CLIENT_ID}
    - O365_CLIENT_SECRET=${O365_CLIENT_SECRET}
    volumes:
      - ./server-config:/server-config
    ports:
      - "8080:8080"
